config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root to: 'pages#home'

  # Souncloud Omniauth

  devise_for :users

  get '/soundcloud/auth', to: 'soundcloud#auth'
  get '/soundcloud/callback', to: 'soundcloud#callback'

  resources :trackers, only: [:show]

  resources :tracks, only: [:show, :new, :create, :destroy, :index] do
    collection do
      get :fresh
      get :trending
    end

    member do
      patch :upvote
      get   :detail
    end

    resources :comments, only: [:create, :destroy]
  end

  resource :profile, only: [:show, :edit, :update, :destroy]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

 def show
    @profile = current_user
    @tracks = current_user.tracks.order(created_at: :desc)
    @upvoted_tracks = Track.joins(:votes).where(votes: { user_id: current_user.id }).select("tracks.*, MAX(votes.created_at) as vote_created_at").order("vote_created_at DESC").group("tracks.id")
    @commented_tracks = Track.joins(:comments).where(comments: { user_id: current_user.id }).select("tracks.*, MAX(comments.created_at) as comment_created_at").order("comment_created_at DESC").group("tracks.id")
  end

  def edit
    @profile
  end

  def update
    if @profile.update(user_params)
      redirect_to user_path
    else
      render action: 'edit'
    end
  end

  private

  def set_profile
    @profile = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :photo, :photo_cache)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(user) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/profiles/_own_comments_method.html.erb
<!-- Displays all the tracks the tracker has commented on. -->
<div class= "container track-item-container">
  <p>Tracks that you commented</p>
  <% tracks.each do |track| %>
    <% if track.soundcloud_permalink_url != nil %>
      <%= render "tracks/track_item", track: track %>
    <% end %>
  <% end %>
</div>

app/views/profiles/_own_tracks_method.html.erb
<div class= "container track-item-container">
  <p>Tracks that you uploaded</p>
  <%= link_to 'Add a new track', new_track_path, class: "btn btn-default" %>
  <% tracks.each do |track| %>
    <% if track.soundcloud_permalink_url != nil %>
      <%= render "tracks/track_item", track: track, page: 'profile' %>
    <% end %>
  <% end %>
</div>

app/views/profiles/_upvote_method.html.erb
<div class= "container track-item-container">
  <p>Tracks that you upvoted</p>
  <% tracks.each do |track| %>
    <% if track.soundcloud_permalink_url != nil %>
      <%= render "tracks/track_item", track: track %>
    <% end %>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="profile-header-wrapper">
  <div class="container profile-header-container text-center">
    <div class="profile-header-infos">
        <%= image_tag current_user.photo_url, class: "avatar-bordered" %>
        <h1><%= current_user.username.capitalize %></h1>
        <h2></h2>
    </div>
  </div>
</div>

<div class="tabs">
  <a class="tab active" data-target="#votes">
    <span><%= current_user.votes.size %></span>
    <h3>Upvotes</h3>
  </a>
  <a class="tab" data-target="#comments">
    <span><%= current_user.comments.size %></span>
    <h3>Comments</h3>
  </a>
  <a class="tab" data-target="#tracks">
    <span><%= current_user.tracks.size %></span>
    <h3>Tracks</h3>
  </a>
</div>

<div class="container text-center">
  <div class="tab-content" id="votes">
    <%= render "upvote_method", tracks: @upvoted_tracks %>
  </div>

  <div class="tab-content hidden" id="comments">
   <%= render "own_comments_method", tracks: @commented_tracks %>
  </div>

  <div class="tab-content hidden" id="tracks">
    <%= render "own_tracks_method", tracks: @tracks %>
  </div>
</div>