config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root to: 'pages#home'

  # Souncloud Omniauth

  devise_for :users

  get '/soundcloud/auth', to: 'soundcloud#auth'
  get '/soundcloud/callback', to: 'soundcloud#callback'

  resources :trackers, only: [:show]

  resources :tracks, only: [:show, :new, :create, :destroy, :index] do
    collection do
      get :fresh
      get :trending
    end

    member do
      patch :upvote
      get   :detail
    end

    resources :comments, only: [:create, :destroy]
  end

  resource :profile, only: [:show, :edit, :update, :destroy]
end

app/models/track.rb
class Track < ActiveRecord::Base
  extend Enumerize

  enumerize :version, in: [:Sketch, :Rough, :Final]
  enumerize :genre, in: [:Ambient, :Classical, :Dancehall, :DeepHouse, :Disco, :DrumnBass, :Electronic, :HipHop, :House, :Jazz, :Metal, :Pop, :Rap, :RnB, :Rock, :Soul, :Techno, :Trance, :TripHop]

  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :name, :genre, :version, :user_id, presence: :true

  scope :fresh, -> do
    where.not(soundcloud_permalink_url: nil).
      # they're sorted by created_at
      order("created_at DESC")
  end

  scope :hot, -> do
    select("tracks.*, count(votes.id) as votes_count").
      # joins the amount of votes to each track (take in account when the track as 0 votes)
      joins("LEFT OUTER JOIN votes ON votes.track_id = tracks.id").
      # tracks need to have a permalink
      where.not(soundcloud_permalink_url:  nil).
      group("tracks.id").
      # the tracks are order by votes, if same amount of votes, by date of creation
      order("votes_count DESC, tracks.created_at DESC")
  end

  scope :trending, -> do
    select("tracks.*, count(votes.id) as votes_count, (count(votes.id) - ((EXTRACT(hour FROM (NOW() - tracks.created_at))) / 12)) as points").
      # joins the amount of votes to each track (take in account when the track as 0 votes)
      joins("LEFT OUTER JOIN votes ON votes.track_id = tracks.id").
      # tracks need to have a permalink
      where.not(soundcloud_permalink_url: nil).
      group("tracks.id").
      # the tracks are order by votes, if same amount of votes, by date of creation
      order("points DESC, tracks.created_at DESC")
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  respond_to :js, only: [:detail, :upvote, :index]

  skip_before_action :authenticate_user!, only: [:index, :fresh, :trending, :show, :detail]
  before_action :find_track, only: [:show, :upvote, :downvote, :detail]

  def fresh
    @tracks = Track.fresh.page(params[:page]).per(3)
  end

  def trending
    @tracks = Track.trending.page(params[:page]).per(3)
  end

  def show
    @comment = Comment.new
  end

  def new
    @track = current_user.tracks.new
  end

  def index
    case params[:tab]
    when "fresh"
      @tracks = Track.fresh
    when "trending"
      @tracks = Track.trending
    else # hot
      @tracks = Track.hot
    end

    @tracks = @tracks.page(params[:page]).per(3)
  end

  def detail
  end

  def create
    @track = current_user.tracks.new(track_params)

    if @track.save
      client = Soundcloud.new(access_token: current_user.token)
      sc_track = client.post('/tracks',
        track: {
          title: @track.name,
          asset_data: params[:file]
        }
      )

      @track.update(
        soundcloud_id: sc_track.id,
        # soundcloud_created_at: sc_track.created_at,
        soundcloud_user_id: sc_track.user_id,
        soundcloud_duration: sc_track.duration,
        # soundcloud_tag_list: sc_track.tag_list,
        # soundcloud_genre: sc_track.genre,
        # soundcloud_description: sc_track.description,
        soundcloud_title: sc_track.title,
        soundcloud_track_type: sc_track.track_type,
        # soundcloud_license: sc_track.license,
        soundcloud_user_playback_count: sc_track.user_playback_count,
        soundcloud_permalink_url: sc_track.permalink_url,
        soundcloud_stream_url: sc_track.stream_url,
        soundcloud_download_url: sc_track.download_url,
        soundcloud_waveform_url: sc_track.waveform_url,
        soundcloud_playback_count: sc_track.playback_count,
        soundcloud_download_count: sc_track.download_count,
        soundcloud_favoritings_count: sc_track.favoritings_count,
        soundcloud_comment_count: sc_track.comment_count,
        soundcloud_uri: sc_track.uri,
        soundcloud_artwork_url: sc_track.artwork_url,
        # soundcloud_downloadable: sc_track.downloadable,
        soundcloud_user_favorite: sc_track.user_favorite,
      )

      redirect_to track_path(@track)
    else
      render :new
    end
  end

  def destroy
    @track = current_user.tracks.find(params[:id])
    @track.destroy

    respond_to do |format|
      format.html { redirect_to profile_path }
      format.js  # <-- will render `app/views/tracks/destroy.js.erb`
    end
  end

  def upvote
    # you can upvote only once
    if !@track.votes.where(user: current_user).exists?
      @track.votes.where(user: current_user).first_or_create
    else
    # you can take your upvote back
      current_user.votes.where(user: current_user)
      @track.votes.where(user: current_user).first.destroy
    end
  end

  private

  def find_track
    @track = Track.find(params[:id])
    update_artwork
  end

  def track_params
    params.require(:track).permit(:name, :genre, :version)
  end

  def update_artwork
    if user_signed_in?
      client = Soundcloud.new(access_token: current_user.token)
    else
      client = Soundcloud.new(
        client_id:     ENV['SOUNDCLOUD_ID'],
        client_secret: ENV['SOUNDCLOUD_SECRET']
      )
    end

    sc_track = client.get("/tracks/#{@track.soundcloud_id}")

    if sc_track.artwork_url
      @track.update(soundcloud_artwork_url: sc_track.artwork_url)
    else
      @track.update(soundcloud_artwork_url: sc_track.user.avatar_url)
    end
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_index.html.erb
<%= render 'shared/collapse' %>
<header id="top" class="header">
  <div class="header-content text-center">
    <div class="padded"></div>
    <div class="test">
      <div class="tagline">Just tracks. No bullshit.</div>
      <div class="learnmore">
      <a href="#Bar" data-toggle="collapse">
          Learn more!
        </a>
      </div>
    </div>
  </div>
</header>

<div class="tabs-home" id="music-tabs">
  <!-- organizes the tabs-->
  <div class="tab-home">
    <%= link_to root_path, class: (tab == "hot" ? 'active' : '') do %>
    Hot
    <% end %>
  </div>
  <!-- calls the trending view page -->
  <div class="tab-home">
    <%= link_to trending_tracks_path, class: (tab == "trending" ? 'active' : '') do %>
    Trending
    <% end %>
  </div>
  <!-- calls the fresh view page -->
  <div class="tab-home">
    <%= link_to fresh_tracks_path, class: (tab == "fresh" ? 'active' : '') do %>
    Fresh
    <% end %>
  </div>
</div>


<!-- displays hot tracks per default -->
<!-- trending and fresh tracks are 2 other routes, they have their own view -->
<div class="tab-content" id="hot">
  <div class="container track-item-container js-tracks">
    <%= render 'tracks/tracks', tracks: @tracks %>
  </div>
  <div class='pagination-helper' data-page="2" data-max-page="<%= @tracks.num_pages %>" data-tab="<%= tab %>">

    Loading more stuff
  </div>
</div>
</div>

app/views/tracks/_track_card.html.erb
<!-- This is the pop-up Modal -->
<div class="track-card">
  <div class="track-card-main">
    <div class='track-card-artwork' style="background: url('<%= image_url track.soundcloud_artwork_url.gsub('-large', '-t500x500') %>')">></div>
    <div class="player-track-main" style="width: 450px;">
      <div class="player" style="background: url('<%= image_url track.soundcloud_artwork_url.gsub('-large', '-t500x500') %>')">
        <div class="waveform">
          <div class="position">
          </div>
          <iframe class="sc-widget" id='sc' src=<%= "//w.soundcloud.com/player/?url=#{track.soundcloud_permalink_url}"%>></iframe>
        </div>
      </div>
    </div>

    <div class="track-info">
      <div class="track-card-upvote track-item-upvote">
        <%= render 'track_upvote', track: track %>
      </div>
      <div class="track-basic">
        <div class='track-card-title'>
          <%= track.name %>
        </div>
        <div class="track-card-artist">
          <%= track.user.username %>
          <div class="play"><i class="fa fa-play"></i></div>
        </div>
      </div>
    </div>

  </div>

  <div class="track-card-sidebar">
    <span class="track-comment-size"><%= pluralize track.comments.size, "comment" %></span>
    <div class='track-card-comments dont-break-out'>
      <div id="comments">
        <% if track.comments.blank? %>
        <span class="no-comments">
          Be the first to leave a comment for <%= track.name %> by <%= track.user.username %>
        </span>
        <% else %>
        <% track.comments.each do |comment| %>
        <%= render 'comments/show', comment: comment %>
        <% end %>
        <% end %>
      </div>
    </div>
    <div class='track-card-sidebar-footer'>
      <%= render 'comments/form', track: track, comment: Comment.new %>
    </div>
  </div>
</div>
</div>

app/views/tracks/_track_item.html.erb
<div class="track-item-container">
  <div class="track-item" id="ti" data-track-id="<%= track.id %>">
    <div class='track-item-upvote'>
      <%= render 'tracks/track_upvote', track: track %>
    </div>
    <div>
     <div class='track-item-name'>
        <%= link_to track.name, detail_track_path(track), remote: true %></div>
        <div class='track-item-genre'>
          <%= track.genre %>
        </div>
      </div>
      <div class='track-item-right'>
            <% if user_signed_in? && current_user == track.user && local_assigns[:page] == 'profile' %>
        <span data-behavior="delete" data-path="<%= track_path(track) %>">
          <i class="fa fa-trash"></i>
        </span>
      <% end %>
        <div class='track-item-version'>
          <bold><%= track.version %></bold>
        </div>
         <div class='track-item-comment'>
           <i class="fa fa-comment-o"></i>
           <%= track.comments.size %>
         </div>
         <div class='track-item-image'>
            <%=link_to tracker_path(track.user_id) do %>
             <%= image_tag track.user.photo_url, class: "avatar-large" %>
            <% end %>
        </div>
      </div>
  </div>
</div>

app/views/tracks/_track_upvote.html.erb
<% if user_signed_in? %>
  <%= link_to upvote_track_path(track), remote: true, method: :patch, class: "track-upvote track-upvote-#{track.id}" do %>
    <div class="track-item-arrow"></div>
    <%= (track.votes.count)%>
  <% end %>
<% else  %>
  <a class="track-upvote track-upvote-#{track.id}" data-toggle="modal" data-target="#modal-signup"%>
    <div class="track-item-arrow"></div>
    <%= (track.votes.count)%>
  </a>
<% end %>

app/views/tracks/_tracks.html.erb
<% tracks.each do |track| %>
  <%= render "tracks/track_item", track: track %>
<% end %>

app/views/tracks/destroy.js.erb
$(".track-item[data-track-id='<%= @track.id %>']").remove();

app/views/tracks/detail.js.erb
var pageTitle  = '<%= j @track.name %> on Track-It'
var urlPath    = "/tracks/<%= @track.id %>"
window.history.pushState('',"", urlPath);
$('.modal-show-container').addClass('is-active')
$('.modal-show').html("<%= j render 'track_card', track: @track %>")

itsTheOnlyProblem()

app/views/tracks/fresh.html.erb
<!-- why the collapse in this partial?
 --><%#= render 'shared/collapse' %>
<%= render 'tracks/index', tab: "fresh" %>

app/views/tracks/index.js.erb
var maxPage = parseInt($('.pagination-helper').data('max-page'))
var pageCount = parseInt($('.pagination-helper').data('page'))
var nextPageCount = pageCount + 1;

if(maxPage >= pageCount) {
  $('.js-tracks').append("<%= j render 'tracks/tracks', tracks: @tracks %>")
  $('.pagination-helper').data('page', nextPageCount)
  window.i = true
} else {
  $('.pagination-helper').remove()
}

app/views/tracks/new.html.erb
<div class="banner_upload">

<div class="banner-content text-center"></div>
<div class= "container form padded">
  <div class= "row">
    <h1>Hey <%= @current_user.username.capitalize %> Upload your Track</h1>

    <%= simple_form_for @track, html: { multipart: true } do |f| %>
    <%= f.input :name %>
    <%= f.input :version %> <!-- input for version is using enumerize, see track model -->
    <%= f.input :genre %>
    <div class="file">
    <%= file_field_tag :file %>
    </div>
    <div class="submit-new">
    <%= f.button :submit %>
    <% end %>
    </div>
  </div>
</div>
</div>

app/views/tracks/show.html.erb
<div class="track-card-container"style= "background:  linear-gradient(rgba(0, 0, 0, 0.9), rgba(0,0,0,0.7)), url('<%= image_url @track.soundcloud_artwork_url %>')">
  <%= render 'track_card', track: @track %>
</div>

app/views/tracks/trending.html.erb
<!-- why the collapse in this partial?
 --><%#= render 'shared/collapse' %>
<%= render 'tracks/index', tab: "trending" %>

app/views/tracks/upvote.js.erb
// $(function() {
//  //$('#upvote').append(new_upvote);
//  //
// });
$(".track-upvote-<%= j @track.id.to_s %>").replaceWith("<%= j render 'tracks/track_upvote', track: @track %>");