config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root to: 'pages#home'

  # Souncloud Omniauth

  devise_for :users

  get '/soundcloud/auth', to: 'soundcloud#auth'
  get '/soundcloud/callback', to: 'soundcloud#callback'

  resources :trackers, only: [:show]

  resources :tracks, only: [:show, :new, :create, :destroy, :index] do
    collection do
      get :fresh
      get :trending
    end

    member do
      patch :upvote
      get   :detail
    end

    resources :comments, only: [:create, :destroy]
  end

  resource :profile, only: [:show, :edit, :update, :destroy]
end

app/views/shared/_collapse.html.erb
<div id="Bar" class="collapse">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h2> Why Track-It? </h2>
      <p class="lead">For the newest and hottest tracks on the web.</p>
      <div class="col-xs-12 col-sm-4">
        <div class="how-it-works-bucket">
          <i class="fa fa-plus-square"></i>
          <h4>Upload your music!</h4>
          <h5>Sign up with your soundcloud my man.</h5>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="how-it-works-bucket">
          <i class="fa fa-music"></i>
          <h4>Listen to the Awesome tracks!</h4>
          <h5>Upvote the most awesome ones.</h5>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="how-it-works-bucket">
          <i class="fa fa-users"></i>
          <h4>Enjoy!</h4>
          <h5>Dont forget to invite your homies.</h5>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <div class="col-lg-12 text-center">
    <a href="#Bar" data-toggle="collapse"><i class="fa fa-angle-double-up"></i></a></div>
    <br>
    <br>
    <br>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<div class='alert-container'>
  <% if notice %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<section>
  <div id="footer">

    <p></p>

</div>
</section>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_pop_sign_in.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="modal-signup">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <p>You need to be logged in to upvote tracks&hellip;</p>
      </div>
      <div class="modal-footer">
        <%= link_to('Login', "/soundcloud/auth", "data-toggle" => "modal")  %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_show.html.erb
<div class='modal-show-container'>
  <div class='modal-show'>
    <!-- <i class="fa fa-times"> -->
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div id="btn">
  <div id='top'></div>
  <div id='middle'></div>
  <div id='bottom'></div>
</div>
<div id="box">
  <div id="items">



    <% if user_signed_in? %>
    <div class="item">
     <%= link_to "/tracks/new" do %>
     <%= t ".profile", default: "Upload" %>
     <%end%>
   </div>
   <% end %>

   <div class="item">
    <%= link_to "/" do %>
    <%= t ".profile", default: "Home" %>
    <% end %>
  </div>

  <% if user_signed_in? %>
  <div class="item">

   <%= link_to "/profile" do %>


   <%= t ".profile", default: "Profile" %>
   <% end %>
 </div>
 <% end %>

 <div class="item">
  <% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>

  <% else %>
  <i class="fa fa-lock"></i>
  <%= link_to('Login', "/soundcloud/auth", "data-toggle" => "modal")  %>
  <% end %>
</div>
</div>
</div>
</div>

app/views/shared/_signin.html.erb
 <!--  SIGN IN Modal -->
 <div class="modal fade" id="user-signin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>
      <div class="modal-body">
        <div class= "container">
          <div class= "row">  
            <%= link_to(image_tag('http://connect.soundcloud.com/2/btn-connect-sc-l.png'), soundcloud_auth_path) %> 
          </div> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_signup.html.erb
 <!-- SIGN UP Modal -->
 <div class="modal fade" id="user-signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <%= simple_form_for(User.new, as: "User", url: user_session_path) do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Signup</h4>
          </div>
          <div class="modal-body">
            <div class= "container form">
              <div class= "row well">  
                <div class="form-group">
                    <div class="form-inputs">
                    <%= f.input :first_name, required: true, autofocus: true %>
                    <%= f.input :last_name, required: true %>
                    <%= f.input :username, required: true %>
                    <%= f.input :email, required: true, autofocus: true %>
                    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
                    <%= f.input :password_confirmation, required: true %>
                        <div class="form-actions">
                        <%= f.button :submit, "Sign up" %>
                        </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_submenu.html.erb
<div class="container text-center" id='sub'>
  <div class="row">
    <ul class="nav nav-tabs">
      <li class="dropdown active">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Upvoted
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Submenu 1-1</a></li>
            <li><a href="#">Submen 1-2</a></li>
            <li><a href="#">Submenu 1-3</a></li> 
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Genre<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Submenu 2-1</a></li>
            <li><a href="#">Submenu 2-2</a></li>
            <li><a href="#">Submenu 2-3</a></li> 
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Status<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Submenu 3-1</a></li>
            <li><a href="#">Submen 3-2</a></li>
            <li><a href="#">Submenu 3-3</a></li> 
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_trackupload.html.erb
<div class="container text-center">
  <div class="row">
    <h1>Hey <%= @current_user.username.capitalize %>!
      <br>
      Drop your Track.</h1>
  </div>
  <div class="row">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Track-It</button>
  </div>



<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="gridSystemModalLabel">
      <div class="modal-body">
        <div class= "container form padded">
          <div class= "row">
            <%= simple_form_for @track, html: { multipart: true } do |f| %>
            <%= f.input :name %>
            <%= f.input :version %> <!-- input for version is using enumerize, see track model -->
            <%= f.input :genre %>
            <%= file_field_tag :file %>
            <br>
            <br>
            <%= f.button :submit %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->